### ISSUE TITLE
Hair Length Bug

### ISSUE THREAD

**Issue by noeinan** [noeinan/DoL-World-Expansion-Mod#84]
note leven (World-Expansion) — 03/30/2021
also, newly created characters do not respect your stylistic choices and force the hair style and length to your preset

FrostBurger — Today at 4:09 AM
Bug - Hair
I know noeinan already acknowledged the existence of this bug but it doesn't seem to be in the Issues section of the github either and as far as I can tell it's not fixed yet so again, here I am. The character image seems to not reflect true hair length but at the same time the game continues to record it growing correctly resulting in my character having longer hair than I think they do.

**Comment by Andrest07** [comment]
Tricky bug surprisingly

**Comment by noeinan** [comment]
I feel like if we look at the areas where I modified hair length, one of them was supposed to be left alone. I'll look at this when I have a moment.

**Comment by Andrest07** [comment]
Seems to me like you only edited one place

**Comment by Andrest07** [comment]
The "bug" I reported never existed. The one note reported is fixed. You might ask how I reported a bug that didn't exist, to that I answer "Because of the fucking sorcery hairstyles are which can make 1000 hairlength look short."

**Comment by Andrest07** [comment]
That shit is even more magic than TFs

**Comment by noeinan** [comment]
Really not sure how me just setting the default caused this...
