### ISSUE TITLE
Ask to change position bug

### ISSUE THREAD

**Issue by Andrest07** [noeinan/DoL-World-Expansion-Mod#94]
![Screenshot_20210410-093521](https://user-images.githubusercontent.com/57931603/114273376-0064ed00-9a44-11eb-9a9a-59717b11e591.jpg)
A bug from asking to change positions, $neckuse wasn't unsetting itself.

**Comment by Andrest07** [comment]
Fixed in bugfixes branch, there was three ask actions that needed it.

**Comment by noeinan** [comment]
Thanks! I forgot about neckuse.
